### ISSUE TITLE
GA

### ISSUE THREAD

**Issue by vitalbone** [picketstudio/site#2]
We should probs put Google Analytics on this thing. Can I leave that with you @davebaskind ?

**Comment by davebaskind** [comment]
Yep!

**Comment by dvbsknd** [comment]
Don't ask me why I'm only looking at this now, but it looks like you'd already added it [a few days after creating the issue](https://github.com/picketstudio/site/commit/6ea572d95746166e1e2b54b751806e4b3380d72d).

**Comment by vitalbone** [comment]
Huh, do you know how to see the reports?

**Comment by dvbsknd** [comment]
I've just added you as an admin individually, but analytics@picketstudio.com will generally get you into any client properties (to which it's been added).

**Comment by vitalbone** [comment]
Thanks. Now I have to learn how to read GA

**Comment by dvbsknd** [comment]
It's bark is way worse than its bite! I can help.
